#ifndef __IhmFormationAjouterFormationEnseignementSuperieur__
#define __IhmFormationAjouterFormationEnseignementSuperieur__


/**
@file
Subclass of AjouterFormationEnseignementSuperieur, which is generated by wxFormBuilder.
*/

#include "Ihm.h"
#include <SqlitePersiBny.h>
#include  <thread>
#include "IhmFormationPrincFrameCatalogue.h"

//// end generated include

/** Implementing AjouterFormationEnseignementSuperieur */
class IhmFormationAjouterFormationEnseignementSuperieur : public AjouterFormationEnseignementSuperieur
{
	protected:
		// Handlers for AjouterFormationEnseignementSuperieur events.
		void buttonConfirmerEvt( wxCommandEvent& event);
		void buttonAnnulerEvt( wxCommandEvent& event );
	public:
		/** Constructor */
		IhmFormationAjouterFormationEnseignementSuperieur( wxWindow* parent);
	//// end generated class members
	
};

#endif // __IhmFormationAjouterFormationEnseignementSuperieur__
