#ifndef __IhmFormationPrincFrameCatalogue__
#define __IhmFormationPrincFrameCatalogue__

/**
@file
Subclass of PrincFrameCatalogue, which is generated by wxFormBuilder.
*/

#include "Ihm.h"

//// end generated include

/** Implementing PrincFrameCatalogue */
class IhmFormationPrincFrameCatalogue : public PrincFrameCatalogue
{
	protected:
		// Handlers for PrincFrameCatalogue events.
		void OnMenuExporterFormation( wxCommandEvent& event );
		void OnMenuAjouterFormationEnseignementSuperieur( wxCommandEvent& event );
		void OnMenuSupprimerFormationEnseignementSuperieur( wxCommandEvent& event );
		void OnMenuModifierFormationEnseignementSuperieur( wxCommandEvent& event );
		//void OnMenuListerFormation( wxCommandEvent& event );
		//void OnMenuDocumentationCRUD( wxCommandEvent& event );
		void OnMenuQuitter( wxCommandEvent& event );
		//void onOuvrirListerEnseignementSuperieur( wxMouseEvent& event );
		//void onFermerListerEnseignementSuperieur( wxMouseEvent& event );
	public:
		/** Constructor */
		IhmFormationPrincFrameCatalogue( wxWindow* parent );
	//// end generated class members
	
};

#endif // __IhmFormationPrincFrameCatalogue__
