#ifndef __IhmFormationSupprimerFormationEnseignementSuperieur__
#define __IhmFormationSupprimerFormationEnseignementSuperieur__

/**
@file
Subclass of SupprimerFormationEnseignementSuperieur, which is generated by wxFormBuilder.
*/

#include "Ihm.h"
#include <wx/wx.h>
#include "SqlitePersiBny.h"
#include  <thread>
#include "IhmFormationPrincFrameCatalogue.h"

//// end generated include

/** Implementing SupprimerFormationEnseignementSuperieur */
class IhmFormationSupprimerFormationEnseignementSuperieur : public SupprimerFormationEnseignementSuperieur
{
	protected:
		// Handlers for SupprimerFormationEnseignementSuperieur events.
		void buttonSupprimerEvt( wxCommandEvent& event);
		void boutonSupprimerToutEvt( wxCommandEvent& event );
		void buttonAnnulerEvt( wxCommandEvent& event );
	public:
		/** Constructor */
		IhmFormationSupprimerFormationEnseignementSuperieur( wxWindow* parent );
	//// end generated class members
	
};

#endif // __IhmFormationSupprimerFormationEnseignementSuperieur__
